channels:
  - conda-forge
  - defaults
dependencies:
  - conda=4.6.2
  - conda-env=2.6.0
  - python=2.7.14
  - python-dateutil=2.6.1
  - numpy=1.12.1
  - pandas=0.23.0
  - py-xgboost=0.72
  - openpyxl=2.4.8
  - scikit-learn=0.19.1
  - scipy=0.19.1
  - statsmodels=0.8.0
  - scandir=1.6
  - sqlite=3.20.1
  - ujson=1.35
  - jsonschema=2.6.0
  - spacy=1.8.2
  - xlrd=1.1.0
  - setuptools
  - pip:
    - hyperopt==0.1.1
    - memory-profiler==0.54.0
    - sqlalchemy==1.1.13
    - psycopg2==2.7.3.2

